name: pm_toast
description: "A Flutter package showcasing customizable toast messages with optional images and buttons, supporting both Android and iOS."
version: 1.0.5
homepage: https://github.com/poorveshinexture312/pm_toast.git

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

